unix {
	interactive 
	cli-listen /run/vpp/cli-vpp1.sock
	full-coredump
	# exec /home/zrf/git/vpp/vpp1.conf
}

api-segment {
	prefix vpp1
}

plugins {
	plugin dpdk_plugin.so { disable } 
}

api-trace {
    on
}
