create host-interface name vpp1vpp2
set interface state host-vpp1vpp2 up
set interface ip address host-vpp1vpp2 2001::1/64

create host-interface name vpp1out
set interface state host-vpp1out up

# 创建二层域，并加入要做SRv6封装的接口
create bridge-domain 1
set interface l2 bridge host-vpp1out 1

# 上行方向
# 配置源SID
set sr encaps source addr 2001:db8:1:1::
# 创建一个BSID（用作SRv6封装规则的标识），next指向SRH中的SID LIST，可以配置多个(TE)
sr policy add bsid 2001:db8:1:1::1 next 2001:db8:2:2:2:: encap
# 把进入lan port接口的流量导入到BSID的转发规则
sr steer l2 host-vpp1out via bsid 2001:db8:1:1::1

# 为封装后的SRv6指明路由
ip route add 2001:db8:2:2:2::/64 via 2001::2

# 解封装规则
sr localsid address 2001:db8:1:1:1:: behavior end.dx2 host-vpp1out
