create host-interface name vpp2vpp1
set interface state host-vpp2vpp1 up
set interface ip address host-vpp2vpp1 2001::2/64

create host-interface name vpp2out
set interface state host-vpp2out up

create bridge-domain 1
set interface l2 bridge host-vpp2out 1

set sr encaps source addr 2001:db8:2:2::
sr policy add bsid 2001:db8:2:2::1 next 2001:db8:1:1:1:: encap
sr steer l2 host-vpp2out via bsid 2001:db8:2:2::1

ip route add 2001:db8:1:1:1::/64 via 2001::1

sr localsid address 2001:db8:2:2:2:: behavior end.dx2 host-vpp2out